### ISSUE TITLE
UNMET PEER DEPENDENCY @angular/platform-browser@4.0.1

### ISSUE THREAD

**Issue by silviodeligios** [seiyria/ng2-sweetalert2#10]
Please update the library dependencies

**Comment by seiyria** [comment]
You're welcome to submit a PR.

**Comment by michael34** [comment]
As far as I understand this is only thrown if your package.json is missing @angular/platform-browser@4.0.1
http://stackoverflow.com/questions/35738346/how-to-solve-npm-unmet-peer-dependency#35738361

**Comment by wolfen351** [comment]
i think this is a update that is required for angular4 support - i have a very similar warning when installing this package:

Logs from the console:
`-- UNMET PEER DEPENDENCY @angular/platform-browser@4.1.2`

`npm WARN ng2-sweetalert2@0.0.8 requires a peer of @angular/platform-browser@^2.0.0-rc.4 but none was installed.`

I think it could maybe be fixed by relaxing the version on the platform-browser - as I already have it installed

From my package.json: 
```
ng-sweet-alert-2": "0.0.4",
"@angular/platform-browser": "^4.1.2",
"@angular/platform-browser-dynamic": "^4.0.0",
```
